# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jellene Khoh
tagline:          'Mashpotato & Rye'
description:      'Programmer · Musician · Artist · Dreamer'
url:              https://jellene4eva.github.io
baseurl:          /

author:
  name:           'jellene4eva'
  url:            https://jellene4eva.github.io

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/jellene4eva/jellene4eva.github.io
