# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jellene Khoh
tagline:
description:      'Mashpotato & Rye'
url:              https://jellene4eva.github.io
baseurl:          /

author:
  name:           'jellene4eva'
  url:            https://jellene4eva.github.io

paginate:         5

# Custom vars
version:          0.0.1

github:           https://github.com/jellene4eva
linkedin:         https://www.linkedin.com/in/jellene-khoh-297571a3/
